import numpy as np

G = 6.67430e-11
TOLERANCE = 1e-6

INITIAL_SUBSTEPS_PER_FRAME = 4
INITIAL_SUBSTEP_DT = 0.01

INITIAL_VIRTUAL_SCREEN_CENTER = np.array([0, 0], dtype=np.float64)
VELOCITY_OF_VIRTUAL_SCREEN_CENTER = 1

INITIAL_VIRTUAL_SCREEN_SIZE = np.array([8, 4.5], dtype=np.float64)
VELOCITY_OF_RESIZE_VIRTUAL_SCREEN = 1.1

SCREEN_SIZE = (1600, 900)
IS_FULL_SCREEN = False
FPS = 60